// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFinance.API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFinance.API.Migrations
{
    [DbContext(typeof(MyFinanceDbContext))]
    [Migration("20260217125815_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFinance.API.Models.AlertaFinanceiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_alerta_financeiro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataAlerta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alerta");

                    b.Property<bool>("Lido")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_lido");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mensagem");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_alerta");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_alerta_financeiro");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_alerta_financeiro_id_usuario");

                    b.ToTable("alerta_financeiro", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.Banco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_banco");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo_banco");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_banco");

                    b.ToTable("banco", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.CartaoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_cartao_credito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_cartao_credito_ativo");

                    b.Property<long?>("BancoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_banco");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<decimal>("LimiteAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("limite_atual");

                    b.Property<decimal>("LimiteTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("limite_total");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_cartao_credito");

                    b.HasIndex("BancoId")
                        .HasDatabaseName("ix_cartao_credito_id_banco");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_cartao_credito_id_usuario");

                    b.ToTable("cartao_credito", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.Carteira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_carteira");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BancoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_banco");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal>("SaldoAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_atual");

                    b.Property<decimal>("SaldoInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("saldo_inicial");

                    b.Property<long>("TipoCarteiraId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_carteira");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_carteira");

                    b.HasIndex("BancoId")
                        .HasDatabaseName("ix_carteira_id_banco");

                    b.HasIndex("TipoCarteiraId")
                        .HasDatabaseName("ix_carteira_id_tipo_carteira");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_carteira_id_usuario");

                    b.ToTable("carteira", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.CategoriaDespesa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_despesa");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Fixo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_fixo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorFixo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_fixo_categoria_despesa");

                    b.HasKey("Id")
                        .HasName("pk_categoria_despesa");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_categoria_despesa_id_usuario");

                    b.HasIndex("Nome", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_despesa_nome_id_usuario");

                    b.ToTable("categoria_despesa", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.CategoriaReceita", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_receita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<bool>("Fixo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_fixo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorFixo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_fixo_categoria_receita");

                    b.HasKey("Id")
                        .HasName("pk_categoria_receita");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_categoria_receita_id_usuario");

                    b.HasIndex("Nome", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_categoria_receita_nome_id_usuario");

                    b.ToTable("categoria_receita", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.Competencia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_competencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<int>("Exercicio")
                        .HasColumnType("integer")
                        .HasColumnName("exercicio");

                    b.Property<int>("Mes")
                        .HasColumnType("integer")
                        .HasColumnName("mes");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_competencia");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_competencia_id_usuario");

                    b.HasIndex("Mes", "Exercicio", "UsuarioId")
                        .IsUnique()
                        .HasDatabaseName("ix_competencia_mes_exercicio_id_usuario");

                    b.ToTable("competencia", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.FaturaCartaoCredito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_fatura_cartao_credito");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CartaoCreditoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_cartao_credito");

                    b.Property<long>("CompetenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_competencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFechamento")
                        .HasColumnType("date")
                        .HasColumnName("data_fechamento_fatura_cartao_credito");

                    b.Property<bool>("Fechada")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_fatura_cartao_credito_fechada");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_fatura_cartao_credito");

                    b.HasKey("Id")
                        .HasName("pk_fatura_cartao_credito");

                    b.HasIndex("CartaoCreditoId")
                        .HasDatabaseName("ix_fatura_cartao_credito_id_cartao_credito");

                    b.HasIndex("CompetenciaId")
                        .HasDatabaseName("ix_fatura_cartao_credito_id_competencia");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_fatura_cartao_credito_id_usuario");

                    b.ToTable("fatura_cartao_credito", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.Investimento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_investimento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<DateOnly?>("DataResgate")
                        .HasColumnType("date")
                        .HasColumnName("data_resgate");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal?>("RendimentoPercentual")
                        .HasColumnType("numeric")
                        .HasColumnName("rendimento_percentual");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_atual");

                    b.Property<decimal>("ValorInicial")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_inicial");

                    b.HasKey("Id")
                        .HasName("pk_investimento");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_investimento_id_usuario");

                    b.ToTable("investimento", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.LancamentoFinanceiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_lancamento_financeiro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CarteiraId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_carteira");

                    b.Property<long?>("CategoriaDespesaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_despesa");

                    b.Property<long?>("CategoriaReceitaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_categoria_receita");

                    b.Property<long?>("CompetenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_competencia");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento_financeiro");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<bool>("Efetivada")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_efetivada");

                    b.Property<long?>("FaturaCartaoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_fatura_cartao_credito");

                    b.Property<bool>("Fixo")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_fixo");

                    b.Property<int?>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<bool>("Parcelado")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_parcelado");

                    b.Property<long>("TipoLancamentoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_lancamento_financeiro");

                    b.Property<int?>("TotalParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("total_parcelas");

                    b.Property<long?>("TransferenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_transferencia_financeira");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_lancamento_financeiro");

                    b.HasKey("Id")
                        .HasName("pk_lancamento_financeiro");

                    b.HasIndex("CarteiraId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_carteira");

                    b.HasIndex("CategoriaDespesaId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_categoria_despesa");

                    b.HasIndex("CategoriaReceitaId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_categoria_receita");

                    b.HasIndex("CompetenciaId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_competencia");

                    b.HasIndex("FaturaCartaoId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_fatura_cartao_credito");

                    b.HasIndex("TipoLancamentoId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_tipo_lancamento_financeiro");

                    b.HasIndex("TransferenciaId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_transferencia_financeira");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_lancamento_financeiro_id_usuario");

                    b.ToTable("lancamento_financeiro", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.MetaFinanceira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_meta_financeira");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Atingida")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_atingida");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date")
                        .HasColumnName("data_fim");

                    b.Property<DateOnly>("DataInicio")
                        .HasColumnType("date")
                        .HasColumnName("data_inicio");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("ValorAtual")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_atual");

                    b.Property<decimal>("ValorMeta")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_meta");

                    b.HasKey("Id")
                        .HasName("pk_meta_financeira");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_meta_financeira_id_usuario");

                    b.ToTable("meta_financeira", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.ParcelaLancamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_parcela_lancamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<long>("LancamentoFinanceiroId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_lancamento_financeiro");

                    b.Property<int>("NumeroParcela")
                        .HasColumnType("integer")
                        .HasColumnName("numero_parcela");

                    b.Property<bool>("Pago")
                        .HasColumnType("boolean")
                        .HasColumnName("fl_pago");

                    b.Property<int>("TotalParcelas")
                        .HasColumnType("integer")
                        .HasColumnName("total_parcelas");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_parcela");

                    b.HasKey("Id")
                        .HasName("pk_parcela_lancamento");

                    b.HasIndex("LancamentoFinanceiroId")
                        .HasDatabaseName("ix_parcela_lancamento_id_lancamento_financeiro");

                    b.ToTable("parcela_lancamento", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.TipoCarteira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_carteira");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipo_carteira");

                    b.ToTable("tipo_carteira", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.TipoLancamentoFinanceiro", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_lancamento_financeiro");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipo_lancamento_financeiro");

                    b.ToTable("tipo_lancamento_financeiro", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.TipoTransferenciaFinanceira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_transferencia_financeira");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_tipo_transferencia_financeira");

                    b.ToTable("tipo_transferencia_financeira", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.TransferenciaFinanceira", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_transferencia_financeira");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("CarteiraDestinoId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_carteira_destino");

                    b.Property<long?>("CarteiraOrigemId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_carteira_origem");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<DateOnly>("DataTransferencia")
                        .HasColumnType("date")
                        .HasColumnName("data_transferencia");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao_transferencia");

                    b.Property<long>("TipoTransferenciaId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tipo_transferencia_financeira");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_transferencia");

                    b.HasKey("Id")
                        .HasName("pk_transferencia_financeira");

                    b.HasIndex("CarteiraDestinoId")
                        .HasDatabaseName("ix_transferencia_financeira_id_carteira_destino");

                    b.HasIndex("CarteiraOrigemId")
                        .HasDatabaseName("ix_transferencia_financeira_id_carteira_origem");

                    b.HasIndex("TipoTransferenciaId")
                        .HasDatabaseName("ix_transferencia_financeira_id_tipo_transferencia_financeira");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_transferencia_financeira_id_usuario");

                    b.ToTable("transferencia_financeira", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("login");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("senha");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_login");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MyFinance.API.Models.AlertaFinanceiro", b =>
                {
                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerta_financeiro_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.CartaoCredito", b =>
                {
                    b.HasOne("MyFinance.API.Models.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .HasConstraintName("fk_cartao_credito_banco_id_banco");

                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_credito_usuario_id_usuario");

                    b.Navigation("Banco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.Carteira", b =>
                {
                    b.HasOne("MyFinance.API.Models.Banco", "Banco")
                        .WithMany()
                        .HasForeignKey("BancoId")
                        .HasConstraintName("fk_carteira_banco_id_banco");

                    b.HasOne("MyFinance.API.Models.TipoCarteira", "TipoCarteira")
                        .WithMany()
                        .HasForeignKey("TipoCarteiraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carteira_tipo_carteira_id_tipo_carteira");

                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_carteira_usuario_id_usuario");

                    b.Navigation("Banco");

                    b.Navigation("TipoCarteira");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.CategoriaDespesa", b =>
                {
                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categoria_despesa_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.CategoriaReceita", b =>
                {
                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categoria_receita_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.Competencia", b =>
                {
                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_competencia_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.FaturaCartaoCredito", b =>
                {
                    b.HasOne("MyFinance.API.Models.CartaoCredito", "CartaoCredito")
                        .WithMany()
                        .HasForeignKey("CartaoCreditoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fatura_cartao_credito_cartao_credito_id_cartao_credito");

                    b.HasOne("MyFinance.API.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fatura_cartao_credito_competencia_id_competencia");

                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fatura_cartao_credito_usuario_id_usuario");

                    b.Navigation("CartaoCredito");

                    b.Navigation("Competencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.Investimento", b =>
                {
                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_investimento_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.LancamentoFinanceiro", b =>
                {
                    b.HasOne("MyFinance.API.Models.Carteira", "Carteira")
                        .WithMany()
                        .HasForeignKey("CarteiraId")
                        .HasConstraintName("fk_lancamento_financeiro_carteira_id_carteira");

                    b.HasOne("MyFinance.API.Models.CategoriaDespesa", "CategoriaDespesa")
                        .WithMany()
                        .HasForeignKey("CategoriaDespesaId")
                        .HasConstraintName("fk_lancamento_financeiro_categoria_despesa_id_categoria_despesa");

                    b.HasOne("MyFinance.API.Models.CategoriaReceita", "CategoriaReceita")
                        .WithMany()
                        .HasForeignKey("CategoriaReceitaId")
                        .HasConstraintName("fk_lancamento_financeiro_categoria_receita_id_categoria_receita");

                    b.HasOne("MyFinance.API.Models.Competencia", "Competencia")
                        .WithMany()
                        .HasForeignKey("CompetenciaId")
                        .HasConstraintName("fk_lancamento_financeiro_competencia_id_competencia");

                    b.HasOne("MyFinance.API.Models.FaturaCartaoCredito", "FaturaCartao")
                        .WithMany()
                        .HasForeignKey("FaturaCartaoId")
                        .HasConstraintName("fk_lancamento_financeiro_fatura_cartao_credito_id_fatura_carta");

                    b.HasOne("MyFinance.API.Models.TipoLancamentoFinanceiro", "TipoLancamento")
                        .WithMany()
                        .HasForeignKey("TipoLancamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lancamento_financeiro_tipo_lancamento_financeiro_id_tipo_la");

                    b.HasOne("MyFinance.API.Models.TransferenciaFinanceira", "Transferencia")
                        .WithMany()
                        .HasForeignKey("TransferenciaId")
                        .HasConstraintName("fk_lancamento_financeiro_transferencia_financeira_id_transfere");

                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lancamento_financeiro_usuario_id_usuario");

                    b.Navigation("Carteira");

                    b.Navigation("CategoriaDespesa");

                    b.Navigation("CategoriaReceita");

                    b.Navigation("Competencia");

                    b.Navigation("FaturaCartao");

                    b.Navigation("TipoLancamento");

                    b.Navigation("Transferencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.MetaFinanceira", b =>
                {
                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_meta_financeira_usuario_id_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MyFinance.API.Models.ParcelaLancamento", b =>
                {
                    b.HasOne("MyFinance.API.Models.LancamentoFinanceiro", "LancamentoFinanceiro")
                        .WithMany()
                        .HasForeignKey("LancamentoFinanceiroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parcela_lancamento_lancamento_financeiro_id_lancamento_fina");

                    b.Navigation("LancamentoFinanceiro");
                });

            modelBuilder.Entity("MyFinance.API.Models.TransferenciaFinanceira", b =>
                {
                    b.HasOne("MyFinance.API.Models.Carteira", "CarteiraDestino")
                        .WithMany()
                        .HasForeignKey("CarteiraDestinoId")
                        .HasConstraintName("fk_transferencia_financeira_carteira_id_carteira_destino");

                    b.HasOne("MyFinance.API.Models.Carteira", "CarteiraOrigem")
                        .WithMany()
                        .HasForeignKey("CarteiraOrigemId")
                        .HasConstraintName("fk_transferencia_financeira_carteira_id_carteira_origem");

                    b.HasOne("MyFinance.API.Models.TipoTransferenciaFinanceira", "TipoTransferencia")
                        .WithMany()
                        .HasForeignKey("TipoTransferenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transferencia_financeira_tipo_transferencia_financeira_id_t");

                    b.HasOne("MyFinance.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_transferencia_financeira_usuario_id_usuario");

                    b.Navigation("CarteiraDestino");

                    b.Navigation("CarteiraOrigem");

                    b.Navigation("TipoTransferencia");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
