INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (1 , 'Ajuste', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (2 , 'Luz', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (3 , 'Água', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (4 , 'TIM', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (5 , 'Netflix', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (6 , 'HBO Max', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (7 , 'Crunchyroll', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (8 , 'Prime Video', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (9 , 'Parcela Apartamento', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (10 , 'Parcela Casa', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (11 , 'Abastecimento', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (12 , 'IPTU Casa', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (13 , 'IPTU Apartamento', TRUE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (14 , 'Empréstimo pessoal', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (15 , 'Compra na maquina para converter em dinheiro', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (16 , 'Veterinário', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (17 , 'Utensílios domésticos', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (18 , 'Conversão de limite em saldo', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (19 , 'Custas advocatícias', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (20 , 'Custas processuais', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (21 , 'Saúde', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (22 , 'Beleza', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (23 , 'Outros', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (24 , 'Internet', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (25 , 'Anuidade cartão crédito', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (26 , 'Alura', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (27 , 'PSN', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (28 , 'Serviços, streams e afins', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (29 , 'Ifood', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (30 , 'Google One', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (31 , 'Uber', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (32 , 'Restaurante', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (33 , 'Supermercado', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (34 , 'Conveniência', FALSE, 1);
INSERT INTO categoria_despesa (id_categoria_despesa, nome, fl_fixo, id_usuario) VALUES (35 , 'Pets', FALSE, 1);