-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2025-08-13T15:20:55.802Z

CREATE TABLE "usuario" (
  "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "login" varchar NOT NULL,
  "senha" varchar(10) NOT NULL,
  "nivel" varchar NOT NULL DEFAULT 'admin',
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "categoria_despesa" (
  "id_categoria_despesa" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "categoria_receita" (
  "id_categoria_receita" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "competencia" (
  "id_competencia" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mes" integer NOT NULL,
  "exercicio" integer NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "tipo_carteira" (
  "id_tipo_carteira" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "carteira" (
  "id_carteira" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "id_tipo_carteira" bigint NOT NULL,
  "saldo_inicial" real NOT NULL DEFAULT 0,
  "saldo_atual" real NOT NULL DEFAULT 0,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "banco" (
  "id_banco" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "codigo_banco" varchar NOT NULL DEFAULT '',
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "cartao_credito" (
  "id_cartao_credito" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_banco" bigint,
  "nome" varchar NOT NULL,
  "limite_total" real NOT NULL DEFAULT 0,
  "limete_atual" real NOT NULL DEFAULT 0,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "fatura_cartao_credito" (
  "id_fatura_carta_credito" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cartao_credito" bigint NOT NULL,
  "id_competencia" bigint NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE UNIQUE INDEX ON "usuario" ("email", "login");

CREATE UNIQUE INDEX ON "categoria_despesa" ("nome", "id_usuario");

CREATE UNIQUE INDEX ON "categoria_receita" ("nome", "id_usuario");

CREATE UNIQUE INDEX ON "competencia" ("mes", "exercicio", "id_usuario");

ALTER TABLE "categoria_despesa" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "categoria_receita" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "competencia" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "carteira" ADD FOREIGN KEY ("id_tipo_carteira") REFERENCES "tipo_carteira" ("id_tipo_carteira");

ALTER TABLE "carteira" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "cartao_credito" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "cartao_credito" ADD FOREIGN KEY ("id_banco") REFERENCES "banco" ("id_banco");

ALTER TABLE "fatura_cartao_credito" ADD FOREIGN KEY ("id_cartao_credito") REFERENCES "cartao_credito" ("id_cartao_credito");

ALTER TABLE "fatura_cartao_credito" ADD FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id_competencia");

ALTER TABLE "fatura_cartao_credito" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");
