-- SQL dump generated using DBML (dbml.dbdiagram.io)
-- Database: PostgreSQL
-- Generated at: 2025-08-14T01:29:57.751Z

CREATE TABLE "usuario" (
  "id_usuario" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar NOT NULL,
  "login" varchar NOT NULL,
  "senha" varchar(10) NOT NULL,
  "nivel" varchar NOT NULL DEFAULT 'admin',
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "categoria_despesa" (
  "id_categoria_despesa" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "categoria_receita" (
  "id_categoria_receita" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "competencia" (
  "id_competencia" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "mes" integer NOT NULL,
  "exercicio" integer NOT NULL,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "banco" (
  "id_banco" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "codigo_banco" varchar NOT NULL DEFAULT '',
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "tipo_carteira" (
  "id_tipo_carteira" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "carteira" (
  "id_carteira" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_banco" bigint,
  "nome" varchar NOT NULL,
  "id_tipo_carteira" bigint NOT NULL,
  "saldo_inicial" real NOT NULL DEFAULT 0,
  "saldo_atual" real NOT NULL DEFAULT 0,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "cartao_credito" (
  "id_cartao_credito" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_banco" bigint,
  "nome" varchar NOT NULL,
  "limite_total" real NOT NULL DEFAULT 0,
  "limite_atual" real NOT NULL DEFAULT 0,
  "fl_cartao_credito_ativo" boolean NOT NULL DEFAULT true,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "fatura_cartao_credito" (
  "id_fatura_cartao_credito" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cartao_credito" bigint NOT NULL,
  "id_competencia" bigint NOT NULL,
  "valor_fatura_cartao_credito" real NOT NULL DEFAULT '0',
  "fl_fatura_cartao_credito_fechada" boolean NOT NULL DEFAULT false,
  "data_fechamento_fatura_cartao_credito" date,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "tipo_transferencia_financeira" (
  "id_tipo_transferencia_financeira" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "transferencia_financeira" (
  "id_transferencia_financeira" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_tipo_transferencia_financeira" bigint NOT NULL,
  "data_transferencia" date NOT NULL DEFAULT 'now()',
  "descricao_transferencia" varchar NOT NULL DEFAULT '',
  "id_carteira_origem" bigint,
  "id_carteira_destino" bigint,
  "id_usuario" bigint NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "tipo_lancamento_financeiro" (
  "id_tipo_lancamento_financeiro" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nome" varchar NOT NULL,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE TABLE "lancamento_financeiro" (
  "id_lancamento_financeiro" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" bigint NOT NULL,
  "data_lancamento_financeiro" date NOT NULL DEFAULT 'now()',
  "id_tipo_lancamento_financeiro" bigint NOT NULL,
  "id_competencia" bigint,
  "id_fatura_cartao_credito" bigint,
  "id_carteira" bigint,
  "id_categoria_receita" bigint,
  "id_categoria_despesa" bigint,
  "id_transferencia_financeira" bigint,
  "fl_parcelado" boolean NOT NULL DEFAULT false,
  "numero_parcela" int,
  "total_parcelas" int,
  "fl_fixo" boolean NOT NULL DEFAULT false,
  "fl_efetivada" boolean NOT NULL DEFAULT false,
  "criado_em" timestamptz NOT NULL DEFAULT 'now()'
);

CREATE UNIQUE INDEX ON "usuario" ("email");

CREATE UNIQUE INDEX ON "usuario" ("login");

CREATE UNIQUE INDEX ON "categoria_despesa" ("nome", "id_usuario");

CREATE UNIQUE INDEX ON "categoria_receita" ("nome", "id_usuario");

CREATE UNIQUE INDEX ON "competencia" ("mes", "exercicio", "id_usuario");

ALTER TABLE "categoria_despesa" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "categoria_receita" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "competencia" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "carteira" ADD FOREIGN KEY ("id_tipo_carteira") REFERENCES "tipo_carteira" ("id_tipo_carteira");

ALTER TABLE "carteira" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "carteira" ADD FOREIGN KEY ("id_banco") REFERENCES "banco" ("id_banco");

ALTER TABLE "cartao_credito" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "cartao_credito" ADD FOREIGN KEY ("id_banco") REFERENCES "banco" ("id_banco");

ALTER TABLE "fatura_cartao_credito" ADD FOREIGN KEY ("id_cartao_credito") REFERENCES "cartao_credito" ("id_cartao_credito");

ALTER TABLE "fatura_cartao_credito" ADD FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id_competencia");

ALTER TABLE "fatura_cartao_credito" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "transferencia_financeira" ADD FOREIGN KEY ("id_tipo_transferencia_financeira") REFERENCES "tipo_transferencia_financeira" ("id_tipo_transferencia_financeira");

ALTER TABLE "transferencia_financeira" ADD FOREIGN KEY ("id_carteira_origem") REFERENCES "carteira" ("id_carteira");

ALTER TABLE "transferencia_financeira" ADD FOREIGN KEY ("id_carteira_destino") REFERENCES "carteira" ("id_carteira");

ALTER TABLE "transferencia_financeira" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_tipo_lancamento_financeiro") REFERENCES "tipo_lancamento_financeiro" ("id_tipo_lancamento_financeiro");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_competencia") REFERENCES "competencia" ("id_competencia");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_fatura_cartao_credito") REFERENCES "fatura_cartao_credito" ("id_fatura_cartao_credito");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_carteira") REFERENCES "carteira" ("id_carteira");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_categoria_receita") REFERENCES "categoria_receita" ("id_categoria_receita");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_categoria_despesa") REFERENCES "categoria_despesa" ("id_categoria_despesa");

ALTER TABLE "lancamento_financeiro" ADD FOREIGN KEY ("id_transferencia_financeira") REFERENCES "transferencia_financeira" ("id_transferencia_financeira");
